import type { Metadata } from "next";
import "./globals.css";
import {Google_Sans_Flex} from "next/font/google";

const googleSansFlex = Google_Sans_Flex({
  variable: "--font-google-sans-flex",
  subsets: ["latin"],
 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${googleSansFlex.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
